# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ahmed\Downloads\final-code-main (3)\final-code-main\final-code\screenInv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1000)
        Form.setMinimumSize(QtCore.QSize(1920, 1000))
        Form.setMaximumSize(QtCore.QSize(1920, 1000))
        Form.setLayoutDirection(QtCore.Qt.RightToLeft)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1590, 10, 241, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #005580;\n"
"font: 20px \"MS Shell Dlg 2\" center\n"
"")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(2600, 30, 41, 31))
        self.label_7.setStyleSheet("background-color: transparent;\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("c:\\Users\\Ahmed\\Downloads\\final-code-main (3)\\final-code-main\\final-code\\../../Downloads/table.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(-330, 0, 2251, 51))
        self.label_8.setStyleSheet("background-color:  #005580")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(1840, 10, 41, 31))
        self.label_9.setStyleSheet("background-color: transparent;\n"
"")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("c:\\Users\\Ahmed\\Downloads\\final-code-main (3)\\final-code-main\\final-code\\../../Downloads/table.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(60, 10, 93, 28))
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setObjectName("back")
        self.download = QtWidgets.QPushButton(Form)
        self.download.setGeometry(QtCore.QRect(180, 10, 93, 28))
        self.download.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download.setObjectName("download")
        self.print = QtWidgets.QPushButton(Form)
        self.print.setGeometry(QtCore.QRect(300, 10, 93, 28))
        self.print.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.print.setStyleSheet("")
        self.print.setObjectName("print")
        self.cover = QtWidgets.QFrame(Form)
        self.cover.setGeometry(QtCore.QRect(0, 54, 1920, 1030))
        self.cover.setStyleSheet("")
        self.cover.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cover.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cover.setObjectName("cover")
        self.frame = QtWidgets.QFrame(self.cover)
        self.frame.setGeometry(QtCore.QRect(270, 80, 1551, 781))
        self.frame.setStyleSheet("background-color:white;\n"
"border:1px solid #005580;\n"
"border-radius:10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(40, 170, 1471, 561))
        self.tableWidget.setStyleSheet("color:black;font-size:16px;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(240)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(31)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(270, 10, 1061, 41))
        self.label_2.setStyleSheet("font-size:30px;\n"
"border:none;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(640, 80, 121, 30))
        self.label_3.setStyleSheet("border:none;font-size:15px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(820, 80, 361, 30))
        self.label_4.setStyleSheet("border:none;font-size:15px;")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(150, 80, 470, 30))
        self.label_10.setStyleSheet("border:none;font-size:15px;")
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(1320, 80, 141, 31))
        self.label_6.setStyleSheet("border:none;font-size:15px;")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.changes = QtWidgets.QPushButton(self.frame)
        self.changes.setGeometry(QtCore.QRect(1290, 740, 93, 28))
        self.changes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changes.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"\n"
"font-size:15px;\n"
"}\n"
"QPushButton:hover{\n"
"border:1px solid #005580;\n"
"background-color:#005580;\n"
"color:white;\n"
"font-size:16px;\n"
"}\n"
"")
        self.changes.setObjectName("changes")
        self.prev = QtWidgets.QPushButton(self.cover)
        self.prev.setGeometry(QtCore.QRect(440, 890, 93, 28))
        self.prev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prev.setStyleSheet("QPushButton{\n"
"\n"
"background-color:#005580;\n"
"color:white;\n"
"font-size:15px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"background-color: #6699ff;\n"
"color:white;\n"
"font-size:16px;\n"
"}\n"
"")
        self.prev.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Ahmed\\Downloads\\final-code-main (3)\\final-code-main\\final-code\\icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev.setIcon(icon)
        self.prev.setObjectName("prev")
        self.next = QtWidgets.QPushButton(self.cover)
        self.next.setGeometry(QtCore.QRect(1570, 880, 91, 28))
        self.next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next.setStyleSheet("QPushButton{\n"
"\n"
"background-color:#005580;\n"
"color:white;\n"
"font-size:15px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"background-color: #6699ff;\n"
"color:white;\n"
"font-size:16px;\n"
"}\n"
"")
        self.next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Ahmed\\Downloads\\final-code-main (3)\\final-code-main\\final-code\\icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon1)
        self.next.setObjectName("next")
        self.printone = QtWidgets.QPushButton(self.cover)
        self.printone.setGeometry(QtCore.QRect(1020, 880, 141, 41))
        self.printone.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.printone.setStyleSheet("QPushButton{\n"
"\n"
"background-color: #005580;\n"
"color:white;\n"
"font-size:15px;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"background-color: #6699ff;\n"
"color:white;\n"
"font-size:16px;\n"
"}\n"
"")
        self.printone.setObjectName("printone")
        self.searchButton = QtWidgets.QPushButton(self.cover)
        self.searchButton.setGeometry(QtCore.QRect(1630, 30, 93, 31))
        self.searchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchButton.setStyleSheet("QPushButton{\n"
"\n"
"background-color: #005580;\n"
"color:white;\n"
"font-size:15px;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"background-color: #6699ff;\n"
"color:white;\n"
"font-size:16px;\n"
"}\n"
"")
        self.searchButton.setObjectName("searchButton")
        self.lineEdit = QtWidgets.QLineEdit(self.cover)
        self.lineEdit.setGeometry(QtCore.QRect(1260, 30, 341, 31))
        self.lineEdit.setStyleSheet("background-color:white;")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox1 = QtWidgets.QComboBox(self.cover)
        self.comboBox1.setGeometry(QtCore.QRect(290, 30, 381, 31))
        self.comboBox1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox1.setStyleSheet("background-color:white;")
        self.comboBox1.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox1.setObjectName("comboBox1")
        self.label_8.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.back.raise_()
        self.download.raise_()
        self.print.raise_()
        self.cover.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "جدول الملاحظين"))
        self.back.setText(_translate("Form", "رجوع"))
        self.download.setText(_translate("Form", "تنزيل"))
        self.print.setText(_translate("Form", "طباعة الكل"))
        self.print.setShortcut(_translate("Form", "Ctrl+P"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "اليوم"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "التكليف"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "اللجان"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "اليوم"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "التكليف"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "اللجان"))
        self.label_2.setText(_translate("Form", "تكليف ملاحظة لجان"))
        self.label_3.setText(_translate("Form", "القسم :"))
        self.label_6.setText(_translate("Form", "السيد/"))
        self.changes.setText(_translate("Form", "حفظ التغيرات"))
        self.prev.setShortcut(_translate("Form", "Left"))
        self.next.setShortcut(_translate("Form", "Right"))
        self.printone.setText(_translate("Form", "طباعه"))
        self.searchButton.setText(_translate("Form", "بحث"))
