# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'screenInv2.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1920, 1080)
        Form.setMinimumSize(QSize(1920, 1080))
        Form.setMaximumSize(QSize(1920, 1080))
        Form.setLayoutDirection(Qt.RightToLeft)
        self.comboBox1 = QComboBox(Form)
        self.comboBox1.setObjectName(u"comboBox1")
        self.comboBox1.setGeometry(QRect(600, 130, 301, 31))
        self.comboBox1.setLayoutDirection(Qt.RightToLeft)
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1590, 10, 241, 31))
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(18, 129, 139);\n"
"font: 20px \"MS Shell Dlg 2\" center\n"
"")
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(540, 230, 821, 711))
        self.frame.setStyleSheet(u"background-color:white;")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(660, 80, 60, 30))
        self.label_3.setLayoutDirection(Qt.RightToLeft)
        self.label_3.setStyleSheet(u"font-size:15px;")
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 80, 571, 30))
        self.label_4.setLayoutDirection(Qt.RightToLeft)
        self.label_4.setStyleSheet(u"font-size:15px;")
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(660, 130, 60, 30))
        self.label_5.setLayoutDirection(Qt.RightToLeft)
        self.label_5.setStyleSheet(u"font-size:15px;")
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(80, 130, 570, 30))
        self.label_6.setLayoutDirection(Qt.RightToLeft)
        self.label_6.setStyleSheet(u"font-size:15px;")
        self.line = QFrame(self.frame)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(40, 190, 731, 3))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.tableWidget = QTableWidget(self.frame)
        if (self.tableWidget.columnCount() < 3):
            self.tableWidget.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(50, 220, 710, 431))
        self.tableWidget.setLayoutDirection(Qt.RightToLeft)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(10)
        self.tableWidget.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(220)
        self.tableWidget.verticalHeader().setMinimumSectionSize(50)
        self.line_2 = QFrame(self.frame)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(70, 250, 680, 3))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 10, 700, 40))
        self.label_2.setLayoutDirection(Qt.RightToLeft)
        self.label_2.setStyleSheet(u"font-size:20px;")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.changes = QPushButton(self.frame)
        self.changes.setObjectName(u"changes")
        self.changes.setGeometry(QRect(612, 670, 141, 28))
        self.changes.setStyleSheet(u"border:none;color:red;font-size:16px;text-decoration: underline;")
        self.lineEdit = QLineEdit(Form)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(990, 130, 200, 30))
        self.searchButton = QPushButton(Form)
        self.searchButton.setObjectName(u"searchButton")
        self.searchButton.setGeometry(QRect(1210, 130, 80, 31))
        self.searchButton.setStyleSheet(u"background-color: rgb(18, 129, 139);font-size:14px;color:white;")
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(2600, 30, 41, 31))
        self.label_7.setStyleSheet(u"background-color: transparent;\n"
"")
        self.label_7.setPixmap(QPixmap(u"../../../Downloads/table.png"))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(-330, 0, 2251, 51))
        self.label_8.setStyleSheet(u"background-color: rgb(18, 129, 139)")
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(1840, 10, 41, 31))
        self.label_9.setStyleSheet(u"background-color: transparent;\n"
"")
        self.label_9.setPixmap(QPixmap(u"../../../Downloads/table.png"))
        self.label_9.setScaledContents(True)
        self.next = QPushButton(Form)
        self.next.setObjectName(u"next")
        self.next.setGeometry(QRect(1240, 960, 93, 28))
        icon = QIcon()
        icon.addFile(u"icons/next.png", QSize(), QIcon.Normal, QIcon.Off)
        self.next.setIcon(icon)
        self.prev = QPushButton(Form)
        self.prev.setObjectName(u"prev")
        self.prev.setGeometry(QRect(570, 960, 93, 28))
        icon1 = QIcon()
        icon1.addFile(u"icons/prev.png", QSize(), QIcon.Normal, QIcon.Off)
        self.prev.setIcon(icon1)
        self.back = QPushButton(Form)
        self.back.setObjectName(u"back")
        self.back.setGeometry(QRect(60, 10, 93, 28))
        self.download = QPushButton(Form)
        self.download.setObjectName(u"download")
        self.download.setGeometry(QRect(180, 10, 93, 28))
        self.printone = QPushButton(Form)
        self.printone.setObjectName(u"printone")
        self.printone.setGeometry(QRect(910, 960, 93, 28))
        self.printone.setStyleSheet(u"background-color: rgb(18, 129, 139);color:white")
        self.print = QPushButton(Form)
        self.print.setObjectName(u"print")
        self.print.setGeometry(QRect(300, 10, 93, 28))
        self.label_8.raise_()
        self.comboBox1.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.lineEdit.raise_()
        self.searchButton.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.next.raise_()
        self.prev.raise_()
        self.back.raise_()
        self.download.raise_()
        self.printone.raise_()
        self.print.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u062c\u062f\u0648\u0644 \u0627\u0644\u0645\u0644\u0627\u062d\u0638\u064a\u0646", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u0627\u0644\u0633\u064a\u062f /", None))
        self.label_4.setText("")
        self.label_5.setText(QCoreApplication.translate("Form", u"\u0642\u0633\u0645 :", None))
        self.label_6.setText("")
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Form", u"\u0627\u0644\u064a\u0648\u0645", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Form", u"\u0627\u0644\u062a\u0643\u0644\u064a\u0641", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Form", u"\u0627\u0644\u0644\u062c\u0627\u0646", None));
        self.label_2.setText(QCoreApplication.translate("Form", u"\u062a\u0643\u0644\u064a\u0641 \u0645\u0644\u0627\u062d\u0638\u0629 \u0644\u062c\u0627\u0646", None))
        self.changes.setText(QCoreApplication.translate("Form", u"\u062d\u0641\u0638 \u0627\u0644\u062a\u063a\u064a\u0631\u0627\u062a", None))
        self.lineEdit.setInputMask("")
        self.searchButton.setText(QCoreApplication.translate("Form", u"\u0628\u062d\u062b", None))
        self.label_7.setText("")
        self.label_8.setText("")
        self.label_9.setText("")
        self.next.setText("")
#if QT_CONFIG(shortcut)
        self.next.setShortcut(QCoreApplication.translate("Form", u"Right", None))
#endif // QT_CONFIG(shortcut)
        self.prev.setText("")
#if QT_CONFIG(shortcut)
        self.prev.setShortcut(QCoreApplication.translate("Form", u"Left", None))
#endif // QT_CONFIG(shortcut)
        self.back.setText(QCoreApplication.translate("Form", u"\u0631\u062c\u0648\u0639", None))
        self.download.setText(QCoreApplication.translate("Form", u"\u062a\u0646\u0632\u064a\u0644", None))
        self.printone.setText(QCoreApplication.translate("Form", u"\u0637\u0628\u0627\u0639\u0629", None))
#if QT_CONFIG(shortcut)
        self.printone.setShortcut(QCoreApplication.translate("Form", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.print.setText(QCoreApplication.translate("Form", u"\u0637\u0628\u0627\u0639\u0629 \u0627\u0644\u0643\u0644", None))
#if QT_CONFIG(shortcut)
        self.print.setShortcut(QCoreApplication.translate("Form", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
    # retranslateUi

