# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ahmed\Downloads\final-code-main (3)\final-code-main\final-code\screenInv1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setMinimumSize(QtCore.QSize(1920, 1080))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1500, 20, 301, 41))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(18, 129, 139);\n"
"font: 30px \"MS Shell Dlg 2\" center\n"
"")
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(1830, 20, 51, 51))
        self.label_8.setStyleSheet("background-color: transparent;\n"
"")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("c:\\Users\\Ahmed\\Downloads\\final-code-main (3)\\final-code-main\\final-code\\icons/table.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(-30, 0, 1951, 81))
        self.label_7.setStyleSheet("background-color: rgb(18, 129, 139)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_not_enough = QtWidgets.QLabel(Form)
        self.label_not_enough.setGeometry(QtCore.QRect(790, 320, 400, 50))
        self.label_not_enough.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_not_enough.setStyleSheet("color:red;font-size:18px")
        self.label_not_enough.setText("")
        self.label_not_enough.setObjectName("label_not_enough")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(820, 560, 231, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(880, 250, 301, 51))
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"text-align:center;\n"
"border: none;\n"
"font-size: 10px;\n"
"color:#8D8D8D;\n"
"font-weight:lighter;")
        self.textBrowser.setObjectName("textBrowser")
        self.help = QtWidgets.QPushButton(Form)
        self.help.setGeometry(QtCore.QRect(940, 730, 101, 31))
        self.help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"color:#2D2D2D;")
        self.help.setIconSize(QtCore.QSize(30, 30))
        self.help.setObjectName("help")
        self.browse = QtWidgets.QPushButton(Form)
        self.browse.setGeometry(QtCore.QRect(1070, 560, 101, 31))
        self.browse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"color:#2D2D2D;")
        self.browse.setIconSize(QtCore.QSize(30, 30))
        self.browse.setObjectName("browse")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(850, 640, 131, 41))
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgb(18, 129, 139);font: 10pt \"MS Shell Dlg 2\";color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(23, 167, 181);\n"
"font-size:11pt;\n"
"}")
        self.back.setIconSize(QtCore.QSize(30, 30))
        self.back.setObjectName("back")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(890, 340, 201, 211))
        self.label_4.setStyleSheet("background-color: transparent;\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("c:\\Users\\Ahmed\\Downloads\\final-code-main (3)\\final-code-main\\final-code\\icons/open-folder.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.generate = QtWidgets.QPushButton(Form)
        self.generate.setGeometry(QtCore.QRect(1000, 640, 131, 41))
        self.generate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generate.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgb(18, 129, 139);font: 10pt \"MS Shell Dlg 2\";color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(23, 167, 181);\n"
"font-size:11pt;\n"
"}")
        self.generate.setIconSize(QtCore.QSize(30, 30))
        self.generate.setObjectName("generate")
        self.label_7.raise_()
        self.label.raise_()
        self.label_8.raise_()
        self.label_not_enough.raise_()
        self.lineEdit.raise_()
        self.textBrowser.raise_()
        self.help.raise_()
        self.browse.raise_()
        self.back.raise_()
        self.label_4.raise_()
        self.generate.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "جدول الملاحظين"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:19pt;\">Excel اختار ملف</span></p></body></html>"))
        self.help.setText(_translate("Form", "مساعدة"))
        self.browse.setText(_translate("Form", "اختار"))
        self.back.setText(_translate("Form", "رجوع"))
        self.generate.setText(_translate("Form", "اكمل"))
