# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ahmed\Downloads\final-code-main (3)\final-code-main\final-code\screenEx2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setMinimumSize(QtCore.QSize(1920, 1080))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1600, 10, 241, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(18, 129, 139);\n"
"font: 20px \"MS Shell Dlg 2\" center\n"
"")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1850, 10, 41, 31))
        self.label_5.setStyleSheet("background-color: transparent;\n"
"")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("c:\\Users\\Ahmed\\Downloads\\final-code-main (3)\\final-code-main\\final-code\\icons/table.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1951, 51))
        self.label_2.setStyleSheet("background-color: rgb(18, 129, 139)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(120, 10, 93, 28))
        self.back.setObjectName("back")
        self.label_2.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.back.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "جدول الامتحانات"))
        self.back.setText(_translate("Form", "رجوع"))
